import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";

const Home: NextPage = (props: any) => {
  const { isLoading, data } = trpc.useQuery(["questions.getAll"]);
  if (isLoading || !data) return <div>Loading...</div>;
  return (
    <div className={""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={""}>
        <code>{data[0]?.question}</code>
      </main>
      <footer></footer>
    </div>
  );
};

export default Home;
